### ISSUE TITLE
path parameter in OA3 spec gets converted to query parameter in generated tests

### ISSUE THREAD

**Issue by daniel-lam-vl** [mzielinski/spring-cloud-contract-oa3#19]
I'm using the spring-cloud-contract-oa3 v3.1.1.0 and it converts the path param of my endpoint as a query param in the generated tests. Am I specifying the contract wrong or is there a bug in spring-cloud-contract-oa3?

Here is an example of an OA3 yaml with path param:

    
    openapi: 3.0.3
        info:
          title: Doughnuts
          version: 0.0.1
          description: |-
            API to make doughnuts
        servers:
          - url: 'http://localhost:8080/'
            description: Local
        paths:
          '/doughnuts/{doughnutId}':
            parameters:
              - schema:
                  type: string
                  example: PEANUT_BUTTER
                name: doughnutId
                in: path
                required: true
                description: Use doughnut to fetch details
                x-contracts:
                  - contractId: 1
                    value: PEANUT_BUTTER
            get:
              summary: Get doughnut by doughnut Id
              x-contracts:
                - contractId: 1
                  name: Should return doughnut by id
              responses:
                '200':
                  description: Ok
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/DoughnutDto'
                  x-contracts:
                    - contractId: 1
                      body:
                        doughnutId: "PEANUT_BUTTER"
                        cost: 1.99
                      headers:
                        Content-Type: application/json
                        
        components:
          schemas:
            DoughnutDto:
              title: DoughnutDto
              type: object
              description: Doughnut data
              properties:
                doughnutId:
                  type: string
                  example: PEANUT_BUTTER
                  description: Doughnutu Identifier
                cost:
                  type: number
                  description: doughnut cost
                  example: 1.99
              required:
                - doughnutId
                - cost
            

Here is the generated test:

         @Test
	  public void validate_should_return_doughnut_by_id() throws Exception {
		  // given:
			  MockMvcRequestSpecification request = given();
  
  
		  // when:
			  ResponseOptions response = given().spec(request)
					  .queryParam("doughnutId","PEANUT_BUTTER")
					  .get("/doughnuts/{doughnutId}");
  
		  // then:
			  assertThat(response.statusCode()).isEqualTo(200);
			  assertThat(response.header("Content-Type")).isEqualTo("application/json");
  
  
		  // and:
			  DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			  assertThatJson(parsedJson).field("['doughnutId']").isEqualTo("PEANUT_BUTTER");
			  assertThatJson(parsedJson).field("['cost']").isEqualTo(1.99);
	  }

**Comment by ChrisCassag** [comment]
_[edited]_
Hey there. I got the exact same behaviour but I figured out a solution. 

You just have to define the `contractPath` in your OA3 yml file at the `get` level:
```
openapi: 3.0.3
    ...
    paths:
      '/doughnuts/{doughnutId}':
        parameters:
          ...
        get:
          ...
          x-contracts:
            - contractId: 1
              name: Should return doughnut by id
              contractPath: /doughnuts/PEANUT_BUTTER
          ...
```

I had to dig a bit to find out, but it's now working like a charm. You may have found it by yourself since then but I am posting anyway in case any other may encounter same issue.

Cheers.

**Comment by mzielinski** [comment]
I made a fix in the code, so now, the original version works as well. 

I expanded it to two parameters to make sure that in such case your example works as well.

I am sorry for delay.
