### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by janeisklar** [mzielinski/spring-cloud-contract-oa3#20]
Are you planning to push your releases to maven central?

**Comment by mzielinski** [comment]
Maybe, in the future. Currently it is pushed to JitPack: https://jitpack.io/#mzielinski/spring-cloud-contract-oa3

It is pretty easy to add additional repository configuration to gradle and maven, so it is enough for now. Nevertheless if there will be such need in the future, we can think about it.

**Comment by mzielinski** [comment]
Maven Central Repository: https://central.sonatype.com/artifact/io.github.mzielinski/spring-cloud-contract-oa3/4.1.4.1
Small change in groupId from `com.github.mzielinski` to `io.github.mzielinski`
