### ISSUE TITLE
Is it possible to use the spring-cloud-contract-oa3 with the OpenApi Specification in JSON format

### ISSUE THREAD

**Issue by ScriptPilotflomix** [mzielinski/spring-cloud-contract-oa3#23]
Hello @mzielinski , I was wondering if it's feasible to employ spring-cloud-contract-oa3 with an OpenAPI specification that's in JSON format. While looking at the examples, I noticed that all the specification files were in YAML, and I couldn't find any that were in JSON

**Comment by mzielinski** [comment]
Sound reasonable. I started to work with this repo again, so I will make this enhancement.

**Comment by mzielinski** [comment]
It is already supported. There is no OpenAPI JSON example in the test. 

I am converting from YAML to JSON automatically, and I check that everything works as expected. 

I did not want to maintain both the JSON and YAML OpenAPI specifications in the source code, so I am performing this conversion automatically in the test.

I assume that we can close this ticket
